version: '3.8'

services:
  wa-bot:
    env_file: '.env'
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./auth_info_baileys:/home/node/app/auth_info_baileys
    container_name: wa-bot
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
    networks:
      - redis-network

  redis:
    image: redis:6.2.5
    command: redis-server --requirepass wabotdev
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: wabotdev
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    networks:
      - redis-network

volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge